#!/usr/bin/env python3
"""Rebuild briefs/briefs.js and insights/insights.js (Python port of tools/build-index.ps1, for the Linux cloud runner).

Usage:  python3 tools/build_index.py
"""
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRIEFS = ROOT / "briefs"
INSIGHTS = ROOT / "insights"
NAME_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-(morning|afternoon|weekend)\.html$")
ORDER = {"morning": 1, "afternoon": 2, "weekend": 1}
S = re.S


def clean(s):
    if not s:
        return ""
    s = re.sub(r"<[^>]+>", "", s)
    s = html.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


def first(pattern, text, flags=0):
    m = re.search(pattern, text, flags)
    return m


def headline(doc):
    zh = en = ""
    m = first(r'<meta name="kp-headline-zh" content="([^"]*)"', doc)
    if m:
        zh = clean(m.group(1))
    m = first(r'<meta name="kp-headline-en" content="([^"]*)"', doc)
    if m:
        en = clean(m.group(1))

    # Format A: first <strong class="zh-t"> followed by the first class="en-t" element
    if not zh:
        m = first(r'<strong class="zh-t">(.*?)</strong>.*?class="en-t"[^>]*>(.*?)</(?:strong|span|div)>', doc, S)
        if m:
            zh = clean(m.group(1))
            en = en or clean(m.group(2))
    # Format B: first alert box <strong>Chinese</strong> <span>English - Source</span>
    if not zh:
        m = first(r'class="alert[^"]*".*?<strong>(.*?)</strong>\s*<span>(.*?)</span>', doc, S)
        if m:
            zh = clean(m.group(1))
            if not en:
                en = re.sub(r"\s+[—·|-]\s+[^—·|]+$", "", clean(m.group(2)))
    # Format C: first <h2>/<h3> holding zh-t / en-t spans
    if not zh:
        m = first(r'<h[23][^>]*>\s*<span class="zh-t">(.*?)</span>\s*<span class="en-t">(.*?)</span>', doc, S)
        if m:
            zh = clean(m.group(1))
            en = en or clean(m.group(2))
    if not zh:
        m = first(r"<h[23][^>]*>(.*?)</h[23]>", doc, S)
        if m:
            zh = clean(m.group(1))
    m = first(r"<title>(.*?)</title>", doc, S)
    title = clean(m.group(1)) if m else ""
    return title, zh or title, en or title


def js_str(s):
    return json.dumps(s, ensure_ascii=False)


def build_briefs():
    items = []
    for f in BRIEFS.glob("*.html"):
        m = NAME_RE.match(f.name)
        if not m:
            continue
        date, slot = m.groups()
        title, zh, en = headline(f.read_text(encoding="utf-8"))
        items.append(dict(file=f.name, date=date, slot=slot, order=ORDER[slot], title=title, zh=zh, en=en))
    items.sort(key=lambda i: (i["date"], i["order"]), reverse=True)
    lines = [
        "  { file: %s, date: %s, slot: %s, order: %d, title: %s, headlineZh: %s, headlineEn: %s }"
        % (js_str(i["file"]), js_str(i["date"]), js_str(i["slot"]), i["order"], js_str(i["title"]), js_str(i["zh"]), js_str(i["en"]))
        for i in items
    ]
    js = "// AUTO-GENERATED by tools/build-index.ps1 - do not edit by hand.\nwindow.BRIEFS = [\n" + ",\n".join(lines) + "\n];\n"
    (BRIEFS / "briefs.js").write_text(js, encoding="utf-8", newline="\n")
    print(f"briefs.js rebuilt with {len(items)} briefs.")
    return items


BOXES = ("dda", "prs", "lump", "bond")
BANNED = ("保证", "稳赚", "必涨", "牢不可破", "封死下行空间", "guarantee", "can't lose", "unshakeable", "risk-free", "无风险")
NO_UPDATE = ("暂无", "无可核实", "无法核实", "no whitelisted", "no verifiable", "could not verify", "no fresh", "no update")


def bitext(o):
    return " ".join(str((o or {}).get(k, "")) for k in ("zh", "en"))


def card_issues(c):
    """Quality problems in one news card or 今日速览 summary (Kelly's rules, 2026-10-02)."""
    out = []
    if c.get("kind") == "summary":
        if not (c.get("figures") or c.get("points")):
            out.append("summary has no figures or points")
        if not ((c.get("takeaway") or {}).get("zh") and (c.get("takeaway") or {}).get("en")):
            out.append("summary missing takeaway zh/en")
        texts = [bitext(c.get("title")), bitext(c.get("takeaway"))] + [bitext(p) for p in c.get("points") or []]
    else:
        if not (c.get("source") or {}).get("url"):
            out.append("missing source.url")
        for k in BOXES:
            o = c.get(k) or {}
            if not (o.get("zh") and o.get("en")):
                out.append(f"box '{k}' missing zh/en")
            elif any(str(o.get(l, "")).lstrip().startswith("🎯") for l in ("zh", "en")):
                out.append(f"box '{k}' repeats its label (starts with 🎯)")
        texts = [bitext(c.get(k)) for k in ("title", "analysis") + BOXES]
    blob = " ".join(texts).lower()
    out += [f"banned word '{w}'" for w in BANNED if w.lower() in blob]
    out += [f"'no update' wording '{w}'" for w in NO_UPDATE if w.lower() in blob]
    return out


def build_insights():
    data = INSIGHTS / "data"
    if not data.is_dir():
        return 0
    parts, count, problems = [], 0, 0
    for f in sorted(data.glob("*.json"), reverse=True):
        raw = f.read_text(encoding="utf-8").strip()
        try:
            arr = json.loads(raw)
        except json.JSONDecodeError as e:
            print(f"WARNING: {f.name} is not valid JSON - skipped ({e})", file=sys.stderr)
            problems += 1
            continue
        if not isinstance(arr, list):
            arr = [arr]
        bad = [c for c in arr if not (c.get("id") and c.get("time") and (c.get("title") or {}).get("zh")
                                      and (c.get("kind") == "summary" or (c.get("source") or {}).get("url")))]
        if bad:
            print(f"WARNING: {f.name}: {len(bad)} card(s) missing id/time/title.zh/source.url - skipped file", file=sys.stderr)
            problems += 1
            continue
        for c in arr:
            for issue in card_issues(c):
                print(f"WARNING: {f.name} {c.get('id')}: {issue}", file=sys.stderr)
                problems += 1
        parts.append(raw)
        count += len(arr)
    js = "// AUTO-GENERATED by tools/build-index.ps1 from insights/data/*.json - do not edit by hand.\nwindow.INSIGHTS = [].concat(\n" + ",\n".join(parts) + "\n);\n"
    (INSIGHTS / "insights.js").write_text(js, encoding="utf-8", newline="\n")
    print(f"insights.js rebuilt with {count} insight cards.")
    return problems


if __name__ == "__main__":
    build_briefs()
    sys.exit(1 if build_insights() else 0)
