# Rebuilds briefs/briefs.js from every brief file named YYYY-MM-DD-<morning|afternoon|weekend>.html
# Usage:  powershell -ExecutionPolicy Bypass -File tools\build-index.ps1
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$briefDir = Join-Path $root 'briefs'
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Clean([string]$s) {
    if (-not $s) { return '' }
    $s = [regex]::Replace($s, '<[^>]+>', '')
    $s = [System.Net.WebUtility]::HtmlDecode($s)
    return ($s -replace '\s+', ' ').Trim()
}
function JsStr([string]$s) {
    return '"' + ($s -replace '\\', '\\' -replace '"', '\"' -replace "`r|`n", ' ') + '"'
}

$order = @{ morning = 1; afternoon = 2; weekend = 1 }
$items = @()
Get-ChildItem $briefDir -Filter '*.html' | Where-Object { $_.Name -match '^(\d{4}-\d{2}-\d{2})-(morning|afternoon|weekend)\.html$' } | ForEach-Object {
    $date = $Matches[1]; $slot = $Matches[2]
    $html = [IO.File]::ReadAllText($_.FullName, $utf8)

    $zh = ''; $en = ''
    # Optional manual override: <meta name="kp-headline-zh" content="..."> / kp-headline-en
    $m = [regex]::Match($html, '<meta name="kp-headline-zh" content="([^"]*)"'); if ($m.Success) { $zh = Clean $m.Groups[1].Value }
    $m = [regex]::Match($html, '<meta name="kp-headline-en" content="([^"]*)"'); if ($m.Success) { $en = Clean $m.Groups[1].Value }

    # Format A: first alert: <strong class="zh-t">...</strong> followed by the first class="en-t" element
    if (-not $zh) {
        $m = [regex]::Match($html, '<strong class="zh-t">(.*?)</strong>.*?class="en-t"[^>]*>(.*?)</(?:strong|span|div)>', 'Singleline')
        if ($m.Success) { $zh = Clean $m.Groups[1].Value; if (-not $en) { $en = Clean $m.Groups[2].Value } }
    }

    # Format B: first alert box: <strong>Chinese</strong> <span>English - Source</span>
    if (-not $zh) {
        $m = [regex]::Match($html, 'class="alert[^"]*".*?<strong>(.*?)</strong>\s*<span>(.*?)</span>', 'Singleline')
        if ($m.Success) {
            $zh = Clean $m.Groups[1].Value
            # drop a trailing " - Source" / " (middot) Source" attribution
            $sep = '[' + [char]0x2014 + [char]0x00B7 + '|-]'
            if (-not $en) { $en = (Clean $m.Groups[2].Value) -replace ('\s+' + $sep + '\s+[^' + [char]0x2014 + [char]0x00B7 + '|]+$'), '' }
        }
    }

    # Format C: first <h2>/<h3> holding zh-t / en-t spans
    if (-not $zh) {
        $m = [regex]::Match($html, '<h[23][^>]*>\s*<span class="zh-t">(.*?)</span>\s*<span class="en-t">(.*?)</span>', 'Singleline')
        if ($m.Success) { $zh = Clean $m.Groups[1].Value; if (-not $en) { $en = Clean $m.Groups[2].Value } }
    }

    # Fallback: first headline-looking element, then the <title>
    if (-not $zh) { $m = [regex]::Match($html, '<h[23][^>]*>(.*?)</h[23]>', 'Singleline'); if ($m.Success) { $zh = Clean $m.Groups[1].Value } }
    $m = [regex]::Match($html, '<title>(.*?)</title>', 'Singleline'); $title = if ($m.Success) { Clean $m.Groups[1].Value } else { '' }
    if (-not $zh) { $zh = $title }
    if (-not $en) { $en = $title }

    $items += [pscustomobject]@{ file = $_.Name; date = $date; slot = $slot; order = $order[$slot]; title = $title; zh = $zh; en = $en }
}

$items = $items | Sort-Object @{ Expression = 'date'; Descending = $true }, @{ Expression = 'order'; Descending = $true }
$lines = foreach ($i in $items) {
    "  { file: $(JsStr $i.file), date: $(JsStr $i.date), slot: $(JsStr $i.slot), order: $($i.order), title: $(JsStr $i.title), headlineZh: $(JsStr $i.zh), headlineEn: $(JsStr $i.en) }"
}
$js = "// AUTO-GENERATED by tools/build-index.ps1 - do not edit by hand.`nwindow.BRIEFS = [`n" + ($lines -join ",`n") + "`n];`n"
[IO.File]::WriteAllText((Join-Path $briefDir 'briefs.js'), $js, $utf8)
Write-Host "briefs.js rebuilt with $($items.Count) briefs."
